# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnorm_cpp <- function(n, Sigma, dv) {
    .Call(`_puniform_mvrnorm_cpp`, n, Sigma, dv)
}

get_var_boot_rmd <- function(Sigma, dv, reps) {
    .Call(`_puniform_get_var_boot_rmd`, Sigma, dv, reps)
}

get_var_boot_fis <- function(Sigma, n, dv, reps) {
    .Call(`_puniform_get_var_boot_fis`, Sigma, n, dv, reps)
}

ml_est <- function(est, tau, yi, vi, ycv) {
    .Call(`_puniform_ml_est`, est, tau, yi, vi, ycv)
}

ml_tau <- function(tau, d, yi, vi, ycv) {
    .Call(`_puniform_ml_tau`, tau, d, yi, vi, ycv)
}

approx_C <- function(yi, tot_var, ycv, est) {
    .Call(`_puniform_approx_C`, yi, tot_var, ycv, est)
}

pdist_nsig <- function(est, tau, yi, vi, param, ycv, method, val, cv_P) {
    .Call(`_puniform_pdist_nsig`, est, tau, yi, vi, param, ycv, method, val, cv_P)
}

trq <- function(est, tau, yi, vi, ycv, param) {
    .Call(`_puniform_trq`, est, tau, yi, vi, ycv, param)
}

